# Generated by Django 5.1.3 on 2025-01-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authapp", "0003_mediaitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/images/"),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="courses/videos/"),
        ),
    ]
